import React from "react";
declare type Props = {
    stroke?: string;
    strokeOpacity?: number;
    strokeDashArray?: string;
    size?: number;
    scales?: any;
    fill?: string;
    fillOpacity?: number;
    method?: "loess" | "linear";
    span?: number;
    band?: number;
    bins?: number;
    level?: number;
    se?: boolean;
    hideTooltip?: boolean;
    markerRadius?: number;
    onMouseOver?: ({ x0 }: any) => void;
    onMouseOut?: () => void;
};
declare const GeomSmooth: React.FC<Props>;
export { GeomSmooth };
